// <auto-generated />
namespace Estetica5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M15_22_05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M15_22_05));
        
        string IMigrationMetadata.Id
        {
            get { return "202105221551546_M15_22_05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
